services:
    ku_ajax.handler:
        class: Ku\AjaxBundle\AjaxHandler
    ku_ajax.handler_listener:
        class: Ku\AjaxBundle\EventListener\AjaxHandlerListener
        arguments: [@ku_ajax.handler, @twig]
        tags:
            - { name: kernel.event_subscriber }